# Generated by Django 3.1.7 on 2021-03-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210314_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendamodel',
            name='criacao',
            field=models.DateField(),
        ),
    ]
