# Generated by Django 3.1.7 on 2021-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20210314_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendamodel',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
