# Generated by Django 3.1.7 on 2021-03-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_vendamodel_nacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendamodel',
            name='dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
