# Generated by Django 3.1.7 on 2021-03-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_auto_20210312_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarteiraModel',
        ),
    ]
