# Generated by Django 3.1.7 on 2021-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210314_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramodel',
            name='data',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compramodel',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compramodel',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
