# Generated by Django 3.1.7 on 2021-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20210314_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramodel',
            name='data',
            field=models.DateField(),
        ),
    ]
