# Generated by Django 3.1.7 on 2021-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210314_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramodel',
            name='nacional',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
