# Generated by Django 3.1.7 on 2021-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compramodel_nacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramodel',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
