# Generated by Django 3.1.7 on 2021-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_carteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniomodel',
            name='vol_br',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrimoniomodel',
            name='vol_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrimoniomodel',
            name='vol_usa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
